INSERT INTO tb_jogos(nome_jogos, genero_jogos, plataforma_jogos, faixaetaria_jogos) VALUES
	('Call of Duty: Warzone', 'FPS', 'Multi-plataforma', 18),
	('Counter-Strike: Global Offensive', 'FPS', 'PC', 18),
	('Overwatch', 'FPS', 'Multi-plataforma', 13),
	('Rainbow Six Siege', 'FPS', 'Multi-plataforma', 18),
	('DOOM Eternal', 'FPS', 'Multi-plataforma', 18),
	('Battlefield V', 'FPS', 'Multi-plataforma', 18),
	('Halo Infinite', 'FPS', 'Multi-plataforma', 18),
  ('FIFA 22', 'Sport', 'Multi-plataforma', 0),
  ('NBA 2K22', 'Sport', 'Multi-plataforma', 0),
  ('Madden NFL 22', 'Sport', 'Multi-plataforma', 0),
  ('Pro Evolution Soccer 2023', 'Sport', 'Multi-plataforma', 0),
  ('MLB The Show 22', 'Sport', 'Console', 0),
  ('Rocket League', 'Sport', 'Multi-plataforma', 0),
  ('Tony Hawks Pro Skater 1 + 2', 'Sport', 'Multi-plataforma', 13),
  ('League of Legends', 'MOBA', 'PC', 13),
  ('Dota 2', 'MOBA', 'PC', 18),
  ('Smite', 'MOBA', 'Multi-plataforma', 13),
  ('Heroes of the Storm', 'MOBA', 'PC', 13),
  ('Arena of Valor', 'MOBA', 'Multi-plataforma', 10),
  ('Vainglory', 'MOBA', 'Mobile', 10),
  ('Mobile Legends: Bang Bang', 'MOBA', 'Mobile', 13),
  ('The Witcher 3: Wild Hunt', 'RPG', 'Multi-plataforma', 18),
  ('Final Fantasy XIV', 'RPG', 'Multi-plataforma', 13),
  ('The Elder Scrolls V: Skyrim', 'RPG', 'Multi-plataforma', 18),
  ('Divinity: Original Sin 2', 'RPG', 'Multi-plataforma', 18),
  ('Dragon Age: Inquisition', 'RPG', 'Multi-plataforma', 18),
  ('Persona 5', 'RPG', 'Console', 13),
  ('Octopath Traveler', 'RPG', 'Console', 13);
